version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/sre.conf:/etc/nginx/conf.d/default.conf
    network_mode: host

  app:
    build: ./app
    network_mode: host
    depends_on: 
     - nginx

  sidecar:
    image: alpine:latest
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock 
      - ./var/run/SliceHealth.sh:/var/run/SliceHealth.sh
    network_mode: host
    depends_on: 
     - nginx    
    command: > 
        sh -c "apk --no-cache add curl && /var/run/SliceHealth.sh"
